In [2]:
import numpy as np

In [4]:
arr = [45,88,96,30]
print(arr)
print(type(arr))
print(arr[2])

[45, 88, 96, 30]
<class 'list'>
96


In [6]:
n_ar = np.array([85,11,36,45])
print(n_ar)
print(type(n_ar))

[85 11 36 45]
<class 'numpy.ndarray'>


In [7]:
print(n_ar[2])

36


In [8]:
print(n_ar*4)

[340  44 144 180]


In [13]:
#Predefined Arrays

#zeros
z1 = np.zeros((2,4))
print(z1)
print(type(z1))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [15]:
#ones
o1 = np.ones((2,4))
print(o1)
print(type(o1)) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [16]:
#full 
f1 = np.full((2,4),15)
print(f1)
print(type(f1))

[[15 15 15 15]
 [15 15 15 15]]
<class 'numpy.ndarray'>


In [17]:
#Ranges
n1 = np.arange(5,15)
print(n1)

[ 5  6  7  8  9 10 11 12 13 14]


In [18]:
n2 = np.arange(5,15,2)
print(n2)

[ 5  7  9 11 13]


In [25]:
#linspace
nln1 = np.linspace(10,20,4)
print(nln1)

[10.         13.33333333 16.66666667 20.        ]


In [23]:
nln2 = np.linspace(1,10,10,dtype=int)
print(nln2)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#random arrays
nrn1 = np.random.rand(2,3) #works as a dimensional matrix
print(nrn1)

[[0.50030286 0.90007553 0.25883711]
 [0.47634416 0.95639103 0.37062505]]


In [38]:
nrn2 = np.random.randint(2,30,(2,3)) #(2,30 works as a range) / (2,3 works as dimensional matrix)
print(nrn2)

[[27 17 16]
 [27 13 16]]


In [39]:
arr10 = np.array([4,8,9,15]) 
arr11 = np.array([2,6,13,17])

In [43]:
print(arr10+arr11)
print(arr10-arr11)
print(arr10*arr11)
print(arr10/arr11)

[ 6 14 22 32]
[ 2  2 -4 -2]
[  8  48 117 255]
[2.         1.33333333 0.69230769 0.88235294]


In [46]:
arr12 = np.array([1,4,9,16])
print(np.sqrt(arr12))
print(np.log(arr12))
print(np.exp(arr12))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [ ]:
#reshape - wrong
arr13 = np.arange(1,7).reshape(3,3)
arr13

ValueError: cannot reshape array of size 6 into shape (3,3)

In [53]:
#reshape - right
arr13 = np.arange(1,7).reshape(2,3)
arr13

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#statistical functions
print(np.sum(arr13))
print(np.mean(arr13))
print(np.std(arr13))
print(np.min(arr13),np.max(arr13))

21
3.5
1.707825127659933
1 6


In [59]:
#dimensionality 
ar2d = np.array(
[
    [1,2,3],
    [4,5,6]
]
)
print(ar2d)
print(ar2d.ndim)
print(ar2d.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [60]:
ar3d = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)
print(ar3d)
print(ar3d.ndim)
print(ar3d.shape)

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)


In [61]:
ar4d = np.ones((2,3,4,5),dtype=int)
print(ar4d)
print(ar4d.ndim)
print(ar4d.shape)

[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]]
4
(2, 3, 4, 5)


In [65]:
arr15 = np.array([5,15,22,39,56])
print(arr15[2])
print(arr15[1:4])
print(arr15[::-1])

22
[15 22 39]
[56 39 22 15  5]
